### ISSUE TITLE
Determine Level 2 and Level 3 Concepts

### ISSUE THREAD

**Issue by Kwyandt** [calebhenry/One-Life-Left#37]
We need to finalize what is expected for each completed levels and transitions 
- [X] Level 1 
- Boss: Roomba 
- Location: Living Room (rugs, couches, plants)
- Enemies: Mice, water guns

- [x] Level 2
- Boss: mice w/water balloon launcher???
- Location: Kitchen
- Enemies: Mice, cheese...?

- [x] Level 3
- Boss: Giant Kind mouse? Dog? Bro idk
- Location: Bedroom?
- Enemies: Mice...?

- [x] Final Animation
- [x] Menu - what happens between each level?

**Comment by GBlackwell1** [comment]
Level 1 has been done, level 2 spooky, level 3 futuristic
